import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.4.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-07",
        enabledModels: [
          "shopifyBulkOperation",
          "shopifyCustomer",
          "shopifyCustomerAddress",
          "shopifyFulfillment",
          "shopifyFulfillmentEvent",
          "shopifyFulfillmentLineItem",
          "shopifyFulfillmentOrder",
          "shopifyFulfillmentOrderLineItem",
          "shopifyLocation",
          "shopifyOrder",
          "shopifyOrderLineItem",
          "shopifyProduct",
          "shopifyProductOption",
          "shopifyProductVariant",
        ],
        type: "partner",
        scopes: [
          "read_locations",
          "unauthenticated_write_customers",
          "write_assigned_fulfillment_orders",
          "write_customers",
          "write_files",
          "write_fulfillments",
          "write_merchant_managed_fulfillment_orders",
          "write_orders",
          "write_payment_customizations",
          "write_products",
          "write_third_party_fulfillment_orders",
          "unauthenticated_read_customers",
          "read_assigned_fulfillment_orders",
          "read_customers",
          "read_files",
          "read_fulfillments",
          "read_merchant_managed_fulfillment_orders",
          "read_orders",
          "read_payment_customizations",
          "read_products",
          "read_third_party_fulfillment_orders",
          "read_order_edits",
          "write_order_edits",
        ],
        customerAuthenticationEnabled: false,
      },
      openai: true,
    },
  },
};
