import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://admin-action-block.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Order",
  fields: {
    cancelReasonBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-cancel_reason::FieldStorageEpoch-DataModel-Shopify-Order-cancel_reason-initial",
    },
    currencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-currency::FieldStorageEpoch-DataModel-Shopify-Order-currency-initial",
    },
    financialStatusBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-financial_status::FieldStorageEpoch-DataModel-Shopify-Order-financial_status-initial",
    },
    fulfillmentStatusBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-fulfillment_status::FieldStorageEpoch-DataModel-Shopify-Order-fulfillment_status-initial",
    },
    number: {
      type: "number",
      storageKey:
        "ModelField-DataModel-Shopify-Order-number::FieldStorageEpoch-DataModel-Shopify-Order-number-initial",
    },
    orderNumber: {
      type: "number",
      storageKey:
        "ModelField-DataModel-Shopify-Order-order_number::FieldStorageEpoch-DataModel-Shopify-Order-order_number-initial",
    },
    presentmentCurrencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Order-presentment_currency::FieldStorageEpoch-DataModel-Shopify-Order-presentment_currency-initial",
    },
    statusPageUrl: {
      type: "url",
      storageKey:
        "ModelField-DataModel-Shopify-Order-__gadget_graphql_status_page_url::FieldStorageEpoch-DataModel-Shopify-Order-__gadget_graphql_status_page_url-initial",
    },
  },
  shopify: {
    fields: [
      "additionalFees",
      "alerts",
      "billingAddress",
      "billingStatusMatchesShippingAddress",
      "browserIp",
      "buyerAcceptsMarketing",
      "canMarkAsPaid",
      "canNotifyCustomer",
      "cancelReason",
      "cancellation",
      "cancelledAt",
      "capturable",
      "cartDiscountAmountSet",
      "cartToken",
      "checkoutToken",
      "clientDetails",
      "closed",
      "closedAt",
      "confirmationNumber",
      "confirmed",
      "currency",
      "currentCartDiscountAmountSet",
      "currentShippingPriceSet",
      "currentSubtotalLineItemsQuantity",
      "currentSubtotalPrice",
      "currentSubtotalPriceSet",
      "currentTotalAdditionalFeesSet",
      "currentTotalDiscounts",
      "currentTotalDiscountsSet",
      "currentTotalDutiesSet",
      "currentTotalPrice",
      "currentTotalPriceSet",
      "currentTotalTax",
      "currentTotalTaxSet",
      "currentTotalWeight",
      "customer",
      "customerJourneySummary",
      "customerLocale",
      "discountApplications",
      "discountCodes",
      "dutiesIncluded",
      "edited",
      "email",
      "estimatedTaxes",
      "financialStatus",
      "fulfillable",
      "fulfillmentEvents",
      "fulfillmentOrders",
      "fulfillmentStatus",
      "fulfillments",
      "fulfillmentsCount",
      "fullyPaid",
      "hasTimelineComment",
      "landingSite",
      "legacyResourceId",
      "lineItems",
      "location",
      "merchantEditable",
      "merchantEditableErrors",
      "merchantOfRecordAppId",
      "name",
      "netPaymentSet",
      "note",
      "noteAttributes",
      "orderStatusUrl",
      "originalTotalAdditionalFeesSet",
      "originalTotalDutiesSet",
      "originalTotalPriceSet",
      "paymentGatewayNames",
      "phone",
      "poNumber",
      "presentmentCurrency",
      "processedAt",
      "processingMethod",
      "purchasingCompany",
      "purchasingCompanyContact",
      "purchasingCompanyLocation",
      "purchasingEntity",
      "referringSite",
      "refundDiscrepencySet",
      "refundable",
      "requiresShipping",
      "restockable",
      "retailLocation",
      "returnStatus",
      "risk",
      "shippingAddress",
      "shop",
      "shopifyCreatedAt",
      "shopifyProtect",
      "shopifyUpdatedAt",
      "sourceIdentifier",
      "sourceName",
      "sourceUrl",
      "subtotalPrice",
      "subtotalPriceSet",
      "tags",
      "taxExempt",
      "taxLines",
      "taxesIncluded",
      "test",
      "token",
      "totalCapturableSet",
      "totalCashRoundingAdjustment",
      "totalDiscounts",
      "totalDiscountsSet",
      "totalLineItemsPrice",
      "totalLineItemsPriceSet",
      "totalOutstanding",
      "totalOutstandingSet",
      "totalPrice",
      "totalPriceSet",
      "totalReceivedSet",
      "totalRefundedSet",
      "totalRefundedShippingSet",
      "totalShippingPriceSet",
      "totalTax",
      "totalTaxSet",
      "totalTipReceived",
      "totalTipReceivedSet",
      "totalWeight",
      "transactions",
      "transactionsCount",
      "unpaid",
    ],
  },
};
