import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://admin-action-block.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    cookieConsentLevel: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-cookie_consent_level::FieldStorageEpoch-DataModel-Shopify-Shop-cookie_consent_level-initial",
    },
    currencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-currency::FieldStorageEpoch-DataModel-Shopify-Shop-currency-initial",
    },
    eligibleForCardReaderGiveaway: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway::FieldStorageEpoch-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway-initial",
    },
    enabledPresentmentCurrenciesBackup: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-enabled_presentment_currencies::FieldStorageEpoch-DataModel-Shopify-Shop-enabled_presentment_currencies-initial",
    },
    forceSsl: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-force_ssl::FieldStorageEpoch-DataModel-Shopify-Shop-force_ssl-initial",
    },
    productImages: {
      type: "hasMany",
      children: {
        model: "shopifyProductImage",
        belongsToField: "shop",
      },
      storageKey:
        "ModelField-DataModel-Shopify-Shop-wNWfI567wpLc::FieldStorageEpoch-DataModel-Shopify-Shop-NoD2FF_5eusH-initial",
    },
    weightUnitBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-weight_unit::FieldStorageEpoch-DataModel-Shopify-Shop-weight_unit-initial",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "alerts",
      "billingAddress",
      "bulkOperations",
      "checkoutApiSupported",
      "city",
      "company",
      "companyAddress",
      "companyContact",
      "companyContactRole",
      "companyContactRoleAssignment",
      "companyLocation",
      "countriesInShippingZones",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "currencyFormats",
      "customerAccounts",
      "customerAccountsV2",
      "customerAddresses",
      "customerEmail",
      "customerMergeables",
      "customers",
      "description",
      "domain",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "files",
      "finances",
      "fulfillmentEvents",
      "fulfillmentLineItems",
      "fulfillmentOrderLineItems",
      "fulfillmentOrders",
      "fulfillments",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "locations",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderLineItems",
      "orderNumberFormatPrefix",
      "orderNumberFormatSuffix",
      "orderTransactions",
      "orders",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "planPublicDisplayName",
      "preLaunchEnabled",
      "primaryLocale",
      "primaryLocation",
      "productMedia",
      "productOptions",
      "productVariantMedia",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "resourceLimits",
      "richTextEditorUrl",
      "setupRequired",
      "shipsToCountries",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "timezoneAbbreviation",
      "timezoneOffset",
      "timezoneOffsetMinutes",
      "transactionalSmsDisabled",
      "unitSystem",
      "url",
      "weightUnit",
      "zipCode",
    ],
  },
};
