api_version = "2025-07"

[[extensions]]
name = "print"
handle = "print"
uid = "26eab53e-5bcc-98f8-8d4e-53667e1bf67ceb5be4e8"
type = "ui_extension"


# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.tsx"
# The target used here must match the target used in the module file (./src/PrintActionExtension.jsx)
target = "admin.order-index.selection-print-action.render"

# Valid extension targets:

# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
